### ISSUE TITLE
Custom balls template

### ISSUE THREAD

**Issue by XVincentX** [liguori/Tetris#1]
Would it be possible to have custom balls template?

![image](https://cloud.githubusercontent.com/assets/1416224/18034625/e009b4ca-6d41-11e6-9f8c-59fd1f15be1d.png)

**Comment by liguori** [comment]
Yes, of course there is a game configuratore embedded but this project need of an implementation for emit flavour. Can you suggest some devices that we can manage for this porpouse?

**Comment by XVincentX** [comment]
![image](https://cloud.githubusercontent.com/assets/1416224/18626312/85c5b058-7e54-11e6-9d23-118d2ea5392f.png)

This should be able to emit ball flavour as well farts and shits ones.
